---
- name: oVirt shutdown VMs
  hosts: localhost
  gather_facts: false
  vars:
    vm_file: "./toTest.csv"
  tasks:
    - name: Read the VM file
      read_csv:
        path: "{{ vm_file }}"
        delimiter: ","
      register: vm_info
      
    - name: Stop VMs
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: stopped
        force: true
        name: "{{ item.1 }}"
        vm_id: "{{ item.0 }}"
      loop: "{{ vm_info.list | default([]) }}"
      when: item.0 is defined and item.1 is defined