---
- name: Shutdown oVirt VMs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if CSV file exists
      stat:
        path: "{{ vm_file }}"
      register: file_stats
    - name: Debug file_stats variable
      debug:
        var: file_stats
    - name: Debug vm_file variable
      debug:
        var: vm_file
    - name: Read VM information from CSV file
      read_csv:
        path: "{{ vm_file }}"
      register: vm_info
    - name: Shutdown VMs
      ovirt_vm:
        name: "{{ item.vm_name }}"
        id: "{{ item.vm_id }}"
        state: stopped
        auth: "{{ ovirt_auth }}"
      with_items: "{{ vm_info.list }}"
    - debug:
        var: vm_info.list
  environment:
    OVIRT_URL: "https://ovirt-engine.avinity.tv/ovirt-engine/api"
    OVIRT_USERNAME: "bzefzoufi@ictv.com"
    OVIRT_PASSWORD: "ZiadW_2022"
  vars:
    ovirt_auth: "env"
